### ISSUE TITLE
how to log in imessage

### ISSUE THREAD

**Issue by wangtubs** [thepaulbenoit/imessageDOS#1]
hi, can you help me to write a script to login imessage with applescript. I know there is a log in method in imessage, but I don't know how to log in with account and password
thanks

**Comment by thepaulbenoit** [comment]
Here's a link with directions on how to log in to iMesssage manually: https://support.apple.com/kb/PH22359?locale=en_US

I can't think of a reason why you'd want to make a script that does it, since you'd need to either hardcode your credentials in or prompt the user for them, and it doesn't take long to do it manually.

**Comment by wangtubs** [comment]
hi, this is done manually. I want to sig in by applescript, is it possible? there is no single tutorial that use applescript to sign in imessage. strange. since applescript is a good automation tool, why it is not possible to sign in with it?

**Comment by mike-bailey** [comment]
>you'd need to either hardcode your credentials in

It may be possible, but if it isn't this is why
